"""
模拟业务场景数据 —— 30 个最核心的高频日常会计业务场景
每个场景包含：业务描述、推荐借方科目、推荐贷方科目、借方金额、贷方金额、校验提示
"""

MOCK_SCENARIOS = [
    # ─── 费用报销类（1-10）────────────────────────────
    {
        "id": 1,
        "description": "昨天请客户吃饭花了800元",
        "debit_account": "管理费用-业务招待费",
        "credit_account": "银行存款",
        "debit_amount": 800.00,
        "credit_amount": 800.00,
        "warning": "业务招待费按发生额60%扣除，最高不超过年销售收入5‰。",
    },
    {
        "id": 2,
        "description": "购买办公用品花了500元",
        "debit_account": "管理费用-办公费",
        "credit_account": "银行存款",
        "debit_amount": 500.00,
        "credit_amount": 500.00,
        "warning": None,
    },
    {
        "id": 3,
        "description": "员工出差报销差旅费1200元",
        "debit_account": "管理费用-差旅费",
        "credit_account": "银行存款",
        "debit_amount": 1200.00,
        "credit_amount": 1200.00,
        "warning": "差旅费需附出差申请单、行程单及发票。",
    },
    {
        "id": 4,
        "description": "支付办公室房租6000元",
        "debit_account": "管理费用-租赁费",
        "credit_account": "银行存款",
        "debit_amount": 6000.00,
        "credit_amount": 6000.00,
        "warning": "金额超过5000元，建议确认是否属于长期待摊费用！",
    },
    {
        "id": 5,
        "description": "支付水电费1500元",
        "debit_account": "管理费用-水电费",
        "credit_account": "银行存款",
        "debit_amount": 1500.00,
        "credit_amount": 1500.00,
        "warning": None,
    },
    {
        "id": 6,
        "description": "支付快递费80元",
        "debit_account": "管理费用-快递费",
        "credit_account": "银行存款",
        "debit_amount": 80.00,
        "credit_amount": 80.00,
        "warning": None,
    },
    {
        "id": 7,
        "description": "支付员工培训费3000元",
        "debit_account": "管理费用-职工教育经费",
        "credit_account": "银行存款",
        "debit_amount": 3000.00,
        "credit_amount": 3000.00,
        "warning": "职工教育经费不超过工资总额8%的部分准予税前扣除。",
    },
    {
        "id": 8,
        "description": "支付审计咨询费10000元",
        "debit_account": "管理费用-中介服务费",
        "credit_account": "银行存款",
        "debit_amount": 10000.00,
        "credit_amount": 10000.00,
        "warning": None,
    },
    {
        "id": 9,
        "description": "支付会议费2000元",
        "debit_account": "管理费用-会议费",
        "credit_account": "银行存款",
        "debit_amount": 2000.00,
        "credit_amount": 2000.00,
        "warning": "会议费需附会议通知、签到表等证明材料。",
    },
    {
        "id": 10,
        "description": "支付办公室维修费800元",
        "debit_account": "管理费用-维修费",
        "credit_account": "银行存款",
        "debit_amount": 800.00,
        "credit_amount": 800.00,
        "warning": "大额维修（超过原值50%）应资本化处理。",
    },

    # ─── 固定资产类（11-15）───────────────────────────
    {
        "id": 11,
        "description": "购买一台电脑8000元",
        "debit_account": "固定资产-电子设备",
        "credit_account": "银行存款",
        "debit_amount": 8000.00,
        "credit_amount": 8000.00,
        "warning": "电子设备折旧年限一般为3年，残值率5%。",
    },
    {
        "id": 12,
        "description": "购买办公桌椅5000元",
        "debit_account": "固定资产-办公家具",
        "credit_account": "银行存款",
        "debit_amount": 5000.00,
        "credit_amount": 5000.00,
        "warning": "办公家具折旧年限一般为5年。",
    },
    {
        "id": 13,
        "description": "购买生产设备10万元",
        "debit_account": "固定资产-机器设备",
        "credit_account": "银行存款",
        "debit_amount": 100000.00,
        "credit_amount": 100000.00,
        "warning": "机器设备折旧年限一般为10年。",
    },
    {
        "id": 14,
        "description": "购买一辆运输货车15万元",
        "debit_account": "固定资产-运输设备",
        "credit_account": "银行存款",
        "debit_amount": 150000.00,
        "credit_amount": 150000.00,
        "warning": "车辆折旧年限一般为4年，购置税应计入原值。",
    },
    {
        "id": 15,
        "description": "计提本月固定资产折旧5000元",
        "debit_account": "管理费用-折旧费",
        "credit_account": "累计折旧",
        "debit_amount": 5000.00,
        "credit_amount": 5000.00,
        "warning": "折旧方法一经确定不得随意变更。",
    },

    # ─── 薪酬社保类（16-19）───────────────────────────
    {
        "id": 16,
        "description": "支付员工工资5万元",
        "debit_account": "应付职工薪酬-工资",
        "credit_account": "银行存款",
        "debit_amount": 50000.00,
        "credit_amount": 50000.00,
        "warning": "大额工资发放，请确认已代扣代缴个人所得税！",
    },
    {
        "id": 17,
        "description": "缴纳社保和公积金12000元",
        "debit_account": "应付职工薪酬-社保公积金",
        "credit_account": "银行存款",
        "debit_amount": 12000.00,
        "credit_amount": 12000.00,
        "warning": "单位承担部分可税前扣除，个人部分从工资代扣。",
    },
    {
        "id": 18,
        "description": "发放中秋节员工福利3000元",
        "debit_account": "应付职工薪酬-职工福利费",
        "credit_account": "银行存款",
        "debit_amount": 3000.00,
        "credit_amount": 3000.00,
        "warning": "职工福利费不超过工资总额14%的部分准予税前扣除。",
    },
    {
        "id": 19,
        "description": "计提本月职工工资6万元",
        "debit_account": "管理费用-工资",
        "credit_account": "应付职工薪酬-工资",
        "debit_amount": 60000.00,
        "credit_amount": 60000.00,
        "warning": "工资计提需与实发数核对，差异做调整分录。",
    },

    # ─── 销售与收款类（20-23）─────────────────────────
    {
        "id": 20,
        "description": "销售商品一批收到货款50000元",
        "debit_account": "银行存款",
        "credit_account": "主营业务收入",
        "debit_amount": 50000.00,
        "credit_amount": 50000.00,
        "warning": "确认收入的同时需计提增值税销项税额。",
    },
    {
        "id": 21,
        "description": "收到客户前欠货款15000元",
        "debit_account": "银行存款",
        "credit_account": "应收账款",
        "debit_amount": 15000.00,
        "credit_amount": 15000.00,
        "warning": None,
    },
    {
        "id": 22,
        "description": "支付广告推广费2500元",
        "debit_account": "销售费用-广告费",
        "credit_account": "银行存款",
        "debit_amount": 2500.00,
        "credit_amount": 2500.00,
        "warning": "广告费不超过年销售收入15%的部分准予扣除。",
    },
    {
        "id": 23,
        "description": "支付商品运输费800元",
        "debit_account": "销售费用-运输费",
        "credit_account": "银行存款",
        "debit_amount": 800.00,
        "credit_amount": 800.00,
        "warning": None,
    },

    # ─── 采购与存货类（24-26）─────────────────────────
    {
        "id": 24,
        "description": "购买原材料一批30000元",
        "debit_account": "原材料",
        "credit_account": "应付账款",
        "debit_amount": 30000.00,
        "credit_amount": 30000.00,
        "warning": "原材料入库需附入库单和质检单。",
    },
    {
        "id": 25,
        "description": "采购商品一批20000元入库",
        "debit_account": "库存商品",
        "credit_account": "应付账款",
        "debit_amount": 20000.00,
        "credit_amount": 20000.00,
        "warning": None,
    },
    {
        "id": 26,
        "description": "购买包装物500元",
        "debit_account": "周转材料-包装物",
        "credit_account": "银行存款",
        "debit_amount": 500.00,
        "credit_amount": 500.00,
        "warning": None,
    },

    # ─── 税费类（27-28）───────────────────────────────
    {
        "id": 27,
        "description": "缴纳本月增值税8000元",
        "debit_account": "应交税费-应交增值税",
        "credit_account": "银行存款",
        "debit_amount": 8000.00,
        "credit_amount": 8000.00,
        "warning": "增值税申报截止日为次月15日，逾期有滞纳金。",
    },
    {
        "id": 28,
        "description": "计提本月企业所得税5000元",
        "debit_account": "所得税费用",
        "credit_account": "应交税费-应交所得税",
        "debit_amount": 5000.00,
        "credit_amount": 5000.00,
        "warning": "企业所得税按季度预缴，年度汇算清缴。",
    },

    # ─── 其他类（29-30）───────────────────────────────
    {
        "id": 29,
        "description": "银行账户收到存款利息200元",
        "debit_account": "银行存款",
        "credit_account": "财务费用-利息收入",
        "debit_amount": 200.00,
        "credit_amount": 200.00,
        "warning": "利息收入应冲减财务费用，而非计入营业外收入。",
    },
    {
        "id": 30,
        "description": "支付银行转账手续费50元",
        "debit_account": "财务费用-手续费",
        "credit_account": "银行存款",
        "debit_amount": 50.00,
        "credit_amount": 50.00,
        "warning": None,
    },
]


def find_scenario(user_input: str):
    """
    根据用户输入的自然语言，模糊匹配最相似的业务场景。
    如果匹配不到，返回 None。
    """
    keyword_map = [
        (["请客", "吃饭", "招待", "餐饮", "业务招待", "宴请", "餐费"], 0),
        (["办公用品", "文具", "打印纸", "笔", "墨盒", "硒鼓", "办公耗材"], 1),
        (["差旅", "出差", "交通", "住宿", "机票", "火车票", "高铁", "打车", "出租车"], 2),
        (["房租", "租金", "租赁", "办公室租", "房屋租赁", "租房"], 3),
        (["水电", "水电费", "物业", "物业费", "电费", "水费"], 4),
        (["快递", "邮寄", "邮费", "快递费", "物流"], 5),
        (["培训", "培训费", "教育", "职工教育", "进修"], 6),
        (["咨询", "咨询费", "审计", "审计费", "律师", "律师费", "顾问"], 7),
        (["会议", "会议费", "研讨会", "论坛"], 8),
        (["维修", "修理", "修缮", "维修费", "修理费"], 9),
        (["电脑", "笔记本", "台式机", "服务器", "显示器"], 10),
        (["办公桌", "办公椅", "文件柜", "家具", "办公家具", "沙发"], 11),
        (["机器", "设备", "生产设备", "机床", "仪器"], 12),
        (["汽车", "车辆", "轿车", "货车", "机动车", "购车"], 13),
        (["折旧", "计提折旧", "累计折旧"], 14),
        (["工资", "薪酬", "薪资", "奖金", "工资发放", "发工资", "工资表"], 15),
        (["社保", "五险", "养老保险", "医疗保险", "失业保险", "公积金", "住房公积金"], 16),
        (["福利", "福利费", "过节", "节日福利", "体检", "员工福利"], 17),
        (["计提工资", "工资计提"], 18),
        (["销售", "销售商品", "卖货", "出售", "销售收入", "主营业务收入"], 19),
        (["货款", "收到货款", "收款", "回款", "客户付款", "收到钱", "收货款"], 20),
        (["广告", "推广", "宣传", "营销", "广告费", "推广费", "宣传费"], 21),
        (["运输", "运费", "物流费", "配送", "送货"], 22),
        (["原材料", "材料", "采购材料", "进货", "买材料", "采购原料"], 23),
        (["库存商品", "商品", "采购商品", "进货商品", "买货"], 24),
        (["包装", "包装物", "包装箱", "包装盒"], 25),
        (["增值税", "交税", "缴税", "缴增值税"], 26),
        (["所得税", "企业所得税", "计提所得税"], 27),
        (["利息", "利息收入", "存款利息"], 28),
        (["手续费", "银行手续费", "转账费", "账户管理费"], 29),
    ]

    for keywords, scenario_id in keyword_map:
        for kw in keywords:
            if kw in user_input:
                return MOCK_SCENARIOS[scenario_id]

    return None
